coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
ignore:
  - "sqlarfs-cli/src/cli.rs"
  - "sqlarfs-cli/src/bin/sqlar.rs"
