name: "Coverage"

on: [push, pull_request, workflow_dispatch]

jobs:
  coverage:
    name: "Coverage"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v4

      - name: "Install stable toolchain"
        run: rustup toolchain install --profile minimal nightly

      - name: "Install cargo-llvm-cov"
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: "Generate code coverage"
        run: cargo llvm-cov --all-features --codecov --output-path codecov.json

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: codecov.json
          fail_ci_if_error: true
